### ISSUE TITLE
Join

### ISSUE THREAD

**Issue by jpacsai** [salv236/js-methods#8]
Array method

- [x] [research](https://www.w3schools.com/jsref/jsref_join.asp)
- [x] exercise

**Comment by jpacsai** [comment]
might need to find new exercise for this method, depends on current exercise

**Comment by salv236** [comment]
seems pretty straight forward the join method enables to customize what separator to use when you convert an array into a string. i.e can be a comma or anything you like in my example i separate each string value with !!

https://github.com/salv236/js-methods/blob/master/array-methods/js/join.js
